#!/usr/bin/env python3
"""
Fetch Bosnia (Islamic Community in BiH — Vaktija) prayer times.

Computes times OFFLINE from the official vaktija.ba static dataset committed at
sources/vaktija/vaktija.json, so there is no runtime API dependency (the public
api.vaktija.ba rate-limits/503s and has no reliable by-date endpoint). This
replicates vaktija.ba's own production formula (src/api/vaktija/daily.mjs):

    time[i] = base.months[m].days[d].vakat[i]
            + differences[location].months[m].vakat[i]
            + (Europe/Sarajevo DST ? 3600 : 0)

`base` times are perpetual (solar position; Sarajevo == location 77, whose
differences are all zero). `differences` are per-location, per-month offsets in
seconds. Refresh vaktija.json only if the Islamic Community revises it.

vakat order: zora(=fajr), izlazak(=sunrise/syuruk), podne(=dhuhr),
ikindija(=asr), akšam(=maghrib), jacija(=isha). There is no separate imsak in
the Bosnian vaktija — zora (dawn) is when the fast begins, so imsak == fajr.

Usage:
  python3 scripts/fetch_vaktija.py [year]      # write prayer-times JSON
  python3 scripts/fetch_vaktija.py --zones      # (re)generate data/zones/BA.yaml
"""

import calendar
import json
import os
import sys
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from utils import month_complete

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(ROOT, "sources", "vaktija", "vaktija.json")
TZ = ZoneInfo("Europe/Sarajevo")

# Sandžak locations (in Serbia/Montenegro, served by IZ BiH) — flagged so the
# GPS/geojson step can route them separately from Bosnia proper.
SANDZAK = {
    "Bijelo Polje", "Gusinje", "Nova Varoš", "Novi Pazar", "Plav", "Pljevlja",
    "Priboj", "Prijepolje", "Rožaje", "Sjenica", "Tutin",
}


def load_data():
    with open(DATA_FILE, encoding="utf-8") as f:
        return json.load(f)


def is_dst(year, month, day):
    """DST state for Europe/Sarajevo, matching vaktija's own check (post-03:00)."""
    return datetime(year, month, day, 3, 0, tzinfo=TZ).dst() != timedelta(0)


def fmt(secs):
    secs %= 86400
    return f"{secs // 3600:02d}:{(secs % 3600) // 60:02d}"


def compute_day(data, loc_id, year, month, day):
    """Return [fajr, sunrise, dhuhr, asr, maghrib, isha] as HH:MM strings."""
    base = data["vaktija"]["months"][month - 1]["days"][day - 1]["vakat"]
    off = data["differences"][loc_id]["months"][month - 1]["vakat"]
    bump = 3600 if is_dst(year, month, day) else 0
    return [fmt(base[i] + off[i] + bump) for i in range(6)]


def fetch(year):
    data = load_data()
    locations = data["locations"]
    written = skipped = 0

    for loc_id in range(len(locations)):
        zone = f"BA{loc_id}"
        for month in range(1, 13):
            out_dir = os.path.join(ROOT, "data", "prayer-times", "BA", zone)
            out_path = os.path.join(out_dir, f"{year}-{month:02d}.json")
            if month_complete(out_path, year, month):
                skipped += 1
                continue

            rows = []
            for day in range(1, calendar.monthrange(year, month)[1] + 1):
                fajr, sunrise, dhuhr, asr, maghrib, isha = compute_day(
                    data, loc_id, year, month, day
                )
                rows.append({
                    "date": f"{year}-{month:02d}-{day:02d}",
                    "imsak": fajr,        # no separate imsak; zora == fajr
                    "fajr": fajr,
                    "syuruk": sunrise,
                    "dhuhr": dhuhr,
                    "asr": asr,
                    "maghrib": maghrib,
                    "isha": isha,
                })

            os.makedirs(out_dir, exist_ok=True)
            with open(out_path, "w", encoding="utf-8") as f:
                json.dump(rows, f, ensure_ascii=False, indent=2)
                f.write("\n")
            written += 1

    print(f"Done: {written} files written, {skipped} skipped "
          f"({len(locations)} zones × 12 months)")


def emit_zones():
    """Generate data/zones/BA.yaml from the location list."""
    data = load_data()
    locations = data["locations"]
    lines = [
        "# Bosnia (Islamic Community in BiH — Vaktija) zones.",
        "# Generated by scripts/fetch_vaktija.py --zones from sources/vaktija/vaktija.json.",
        "# shapes: TODO — geoBoundaries BA ADM2 mapping for GPS resolution not yet built.",
        "# Sandžak cities (state: Sandžak) are in RS/ME; route their geojson separately.",
        "zones:",
    ]
    for loc_id, name in enumerate(locations):
        state = "Sandžak" if name in SANDZAK else "Bosna i Hercegovina"
        lines += [
            f"  - code: BA{loc_id}",
            f"    country: BA",
            f"    state: {state}",
            f"    location: {name}",
            f"    timezone: Europe/Sarajevo",
            f"    shapes: []",
            "",
        ]
    out = os.path.join(ROOT, "data", "zones", "BA.yaml")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {out} ({len(locations)} zones)")


def main():
    if "--zones" in sys.argv[1:]:
        emit_zones()
        return
    year = int(sys.argv[1]) if len(sys.argv) > 1 else datetime.now().year
    fetch(year)


if __name__ == "__main__":
    main()
