name: Keepalive

on:
  schedule:
    - cron: '0 0 1 * *'  # 1st of each month

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
